version: '3.8'

services:
  # Backend Flask API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: aksharjobs-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
    volumes:
      # Mount source code for live development
      - ./backend:/app
      # Exclude node_modules and other unnecessary files
      - /app/__pycache__
      - /app/venv
      - /app/venv38
    networks:
      - aksharjobs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aksharjobs-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - aksharjobs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  aksharjobs-network:
    driver: bridge

volumes:
  backend-cache:
